<main>
    <h2>
        <?= $pageTitle; ?>
    </h2>

    <form method="post" action="controllers/user-form.php">
        <label for="email">Adresse email :</label>
        <input type="email" id="email" name="email" required>

        <label for="password">Mot de passe :</label>
        <input type="password" id="password" name="password" required>

        <button type="submit">Soumettre</button>
    </form>

    <form method="post" action="controllers/user-form.php">
        <label for="email2">Adresse email :</label>
        <input type="email" id="email2" name="email" required>

        <label for="password2">Mot de passe :</label>
        <input type="password" id="password2" name="password" required>

        <label for="password_confirm">Confirmation du mot de passe :</label>
        <input type="password" id="password_confirm" name="password_confirm" required>

        <label>
            <input type="checkbox" name="newsletter" value="1">
            S'inscrire à la newsletter
        </label>

        <button type="submit">Soumettre</button>
    </form>
</main>